ppnm1/main/urls.py
from django.conf import settings
from django.urls import path
from django.conf.urls.static import static

from . import views


app_name = 'main'


urlpatterns = [
    path('gallery/', views.gallery, name='gallery'),
    path('book/<int:pk>/', views.book, name='book'),
	path('', views.index, name='index'),
]


if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

ppnm1/ppnm1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404, handler500, handler403, handler400
from core.views import error_404, error_500


handler404 = error_404
handler500 = error_500


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('chess/', include('chess_spreadsheet.urls', namespace='chess')),
	path('', include('main.urls', namespace='main')),
]

ppnm1/users/urls.py
from django.contrib.auth.views import (
    LogoutView,
    LoginView
)
from django.urls import path


app_name = 'users'


urlpatterns = [
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
]

ppnm1/templates/users/logged_out.html
{% extends 'base.html' %}

{% block title %}
    Вы вышли из системы
{% endblock %}

{% block content %}
    <div class="row justify-content-center">
        <div class="col-md-8 p-5">
            <div class="card">
                <div class="card-header">
                    Выход
                </div>
                <div class="card-body">
                    <p>Вы вышли из своей учётной записи.</p>
                    <a class="btn btn-primary" href="{% url 'users:login' %}">Войти снова</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

ppnm1/templates/users/login.html
{% extends "base.html" %}

{% block title %}
    Войти
{% endblock %}

{% block content %}
    <div class="row justify-content-center">
        <div class="col-md-8 p-5">
            <div class="card">
                <div class="card-header">
                    Войти в учётную запись
                </div>
                <div class="card-body">
                    {% include 'includes/form_errors.html' %}
                    <form method="post">
                        {% include 'includes/form_body.html' %}
                        <div class="col-md-6">
                            <button type="submit" class="btn btn-primary">
                                Войти
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}