ppnm1/chess_spreadsheet/urls.py
from django.urls import path

from . import views, json_views, all_views, detail_views, create_views


app_name = 'chess'


urlpatterns = [
    path('set_booking_status/', json_views.set_booking_status, name='set_booking_status'),
    path('set_client/', json_views.set_client, name='set_client'),
    path('set_object/', json_views.set_object, name='set_object'),
    path('set_service/', json_views.set_service, name='set_service'),
    path('set_booking/', json_views.set_booking, name='set_booking'),
    
    path('objects/', all_views.objects, name='all_objects'),
    path('clients/', all_views.clients, name='all_clients'),
    path('bookings/', all_views.bookings, name='all_bookings'),
    path('services/', all_views.services, name='all_services'),

    path('objects/<int:pk>/', detail_views.object, name='object_detail'),
    path('clients/<int:pk>/', detail_views.client, name='client_detail'),
    path('bookings/<int:pk>/', detail_views.booking, name='booking_detail'),
    path('services/<int:pk>/', detail_views.service, name='service_detail'),

    path('objects/create/', create_views.object, name='create_object'),
    path('clients/create/', create_views.client, name='create_client'),
    path('bookings/create/', create_views.booking, name='create_booking'),
    path('services/create/', create_views.service, name='create_service'),

    path('calc_game/', views.calc_game, name='calc_game'),
    
	path('employee/', views.employee_window, name='employee'),
    path('<str:date>/', views.chess, name='chess'),


    path('', views.chess_today, name='chess_today')
]

ppnm1/main/urls.py
from django.conf import settings
from django.urls import path
from django.conf.urls.static import static

from . import views


app_name = 'main'


urlpatterns = [
    path('gallery/', views.gallery, name='gallery'),
    path('book/<int:pk>/', views.book, name='book'),
	path('', views.index, name='index'),
]


if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

ppnm1/ppnm1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404, handler500, handler403, handler400
from core.views import error_404, error_500


handler404 = error_404
handler500 = error_500


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('chess/', include('chess_spreadsheet.urls', namespace='chess')),
	path('', include('main.urls', namespace='main')),
]

ppnm1/chess_spreadsheet/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField


class Client(models.Model):
    name = models.CharField('Имя', max_length=200)
    phone_number = PhoneNumberField(
        unique=True,
        verbose_name='Номер телефона'
    )
    email = models.EmailField(
        'Почта',
        null=True,
        blank=True
    )
    self = models.ForeignKey(
        'self',
        on_delete=models.DO_NOTHING,
        related_name='client',
        null=True,
        blank=True
    )

    def __str__(self):
        return self.name


class Object(models.Model):
    title = models.CharField('Название', max_length=50)
    price = models.IntegerField('Цена')
    description = models.TextField('Описание', blank=True, default='')
    self = models.ForeignKey(
        'self',
        on_delete=models.DO_NOTHING,
        related_name='object',
        null=True,
        blank=True
    )

    def __str__(self):
        return f'{self.title} [{self.price} руб.]'


class Service(models.Model):
    title = models.CharField('Название', max_length=50)
    price = models.IntegerField('Цена')
    description = models.TextField('Описание', blank=True, default='')
    self = models.ForeignKey(
        'self',
        on_delete=models.DO_NOTHING,
        related_name='service',
        null=True,
        blank=True
    )

    def __str__(self):
        return f'{self.title} [{self.price} руб.]'


class Booking(models.Model):
    STATUS_CHOICES = [
        ('1', 'Новая бронь'),
        ('2', 'Ожидание клиента'),
        ('3', 'Клиент приехал'),
        ('4', 'Клиент уехал'),
        ('5', 'Отмена'),
    ]
    status = models.CharField(
        max_length=20, choices=STATUS_CHOICES, default='1'
    )
    client = models.ForeignKey(
        Client,
        on_delete=models.PROTECT,
        verbose_name='Клиент',
        related_name='booking'
    )
    customers_count = models.IntegerField(
        'Количество посетителей',
        default=1
    )
    object = models.ForeignKey(
        Object,
        on_delete=models.SET_NULL,
        null=True,
        verbose_name='Объект',
        related_name='booking'
    )
    services = models.ManyToManyField(
        Service,
        verbose_name='Доп. услуги',
        related_name='booking',
        blank=True
    )
    date = models.DateField(
        'Дата брони'
    )
    time_from = models.TimeField(
        'Время начала брони'
    )
    time_to = models.TimeField(
        'Время конца брони'
    )
    pub_date = models.DateTimeField(
        'Дата бронирования',
        auto_now_add=True
    )
    self = models.ForeignKey(
        'self',
        on_delete=models.DO_NOTHING,
        related_name='booking',
        null=True,
        blank=True
    )

    def get_sum(self) -> int:
        res = int(self.object.price)
        for service in self.services.all():
            res += int(service.price)
        return res

    def __str__(self):
        return f'№{self.pk} {self.client} [{self.get_sum()} руб.]'

ppnm1/chess_spreadsheet/forms.py
from django.forms import ModelForm

from .models import Client, Object, Service, Booking


class ClientForm(ModelForm):
    class Meta:
        model = Client
        exclude = ['self',]


class ObjectForm(ModelForm):
    class Meta:
        model = Object
        exclude = ['self']


class ServiceForm(ModelForm):
    class Meta:
        model = Service
        exclude = ['self',]


class BookingForm(ModelForm):
    class Meta:
        model = Booking
        exclude = ['self', 'status']

ppnm1/chess_spreadsheet/views.py
from datetime import datetime

from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from django.urls import reverse

from .models import Object, Booking


@login_required
def employee_window(request):
    context = {
        'bookings': Booking.objects.all()
    }
    return render(request, 'chess_spreadsheet/employee_window.html', context)


def __get_hour(time):
    return datetime.strptime(time.strftime('%H'), '%H').hour


def __time_difference(time_from, time_to):
    return __get_hour(time_to) - __get_hour(time_from) + 1


@login_required
def chess(request, date):
    date = datetime.strptime(date, '%Y-%m-%d').date()
    bookings = Booking.objects.filter(date=date)

    context = {
        'time': [i for i in range(24)],
        'date': date,
        'bookings': [{
            'time': __get_hour(element.time_from),
            'hours_count': __time_difference(
                element.time_from,
                element.time_to
            ),
            'booking': element,
        } for element in bookings],
        'objects': Object.objects.filter(booking__in=bookings)
    }
    return render(request, 'chess_spreadsheet/chess.html', context)


@login_required
def chess_today(request):
    return redirect(reverse(
        'chess:chess',
        args=[datetime.today().strftime('%Y-%m-%d')]
    ))


def calc_game(request):
    return render(request, 'chess_spreadsheet/calc_game.html')

ppnm1/templates/chess_spreadsheet/all_bookings.html
{% extends 'chess_base.html' %}

{% block title %}
    Все брони
{% endblock %}

{% block header_brand %}
    Брони
{% endblock %}

{% block content %}
    {% include 'includes/bookings_table.html' %}
{% endblock %}

ppnm1/templates/chess_spreadsheet/all_clients.html
{% extends 'chess_base.html' %}

{% block title %}
    Все клиенты
{% endblock %}

{% block header_brand %}
    Клиенты
{% endblock %}

{% block header_create %}
    <a class="btn btn-primary" href="{% url 'chess:create_client' %}">Создать</a>
{% endblock%}

{% block content %}
    {% if clients %}
        <table class="table table-striped">
            <thead class="text-center">
                <tr>
                    <th></th>
                    <th scope="col">Имя</th>
                    <th scope="col">Телефон</th>
                    <th scope="col">Email</th>
                </tr>
            </thead>
            <tbody class="align-middle text-center">
                {% for client in clients %}
                    <tr>
                        <td>
                            <a class="nav-link" href="{% url 'chess:client_detail' client.pk %}">#</a>
                        </td>
                        <td>{{ client.name }}</td>
                        <td><a style="text-decoration:none;" href="tel:{{ client.phone_number }}">{{ client.phone_number }}</a></td>
                        <td>{{ client.email }}</td>
                    <tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <h3 class="lead">Клиентов нет</h3>
    {% endif %}
{% endblock %}

ppnm1/templates/chess_spreadsheet/all_objects.html
{% extends 'chess_base.html' %}
{% load user_filters %}

{% block title %}
    Все объекты
{% endblock %}

{% block header_brand %}
    Объекты
{% endblock %}

{% block header_create %}
    <a class="btn btn-primary" href="{% url 'chess:create_object' %}">Создать</a>
{% endblock%}

{% block content %}
    {% if objects %}
        <table class="table table-striped">
            <thead class="text-center">
                <tr>
                    <th></th>
                    <th scope="col">Название</th>
                    <th scope="col">Цена</th>
                    <th scope="col">Описание</th>
                </tr>
            </thead>
            <tbody class="align-middle text-center">
                {% for object in objects %}
                    <tr>
                        <td>
                            <a class="nav-link" href="{% url 'chess:object_detail' object.pk %}">#</a>
                        </td>
                        <td>{{ object.title }}</td>
                        <td>{{ object.price|rus_money }}</td>
                        <td>{% firstof object.description|truncatechars:15|description_add '-пусто-'%}</td>
                    <tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <h3 class="lead">Объектов нет</h3>
    {% endif %}
{% endblock %}

ppnm1/templates/chess_spreadsheet/all_services.html
{% extends 'chess_base.html' %}
{% load user_filters %}

{% block title %}
    Все услуги
{% endblock %}

{% block header_brand %}
    Услуги
{% endblock %}

{% block header_create %}
    <a class="btn btn-primary" href="{% url 'chess:create_service' %}">Создать</a>
{% endblock%}

{% block content %}
    {% if services %}
        <table class="table table-striped">
            <thead class="text-center">
                <tr>
                    <th></th>
                    <th scope="col">Название</th>
                    <th scope="col">Цена</th>
                    <th scope="col">Описание</th>
                </tr>
            </thead>
            <tbody class="align-middle text-center">
                {% for service in services %}
                    <tr>
                        <td>
                            <a class="nav-link" href="{% url 'chess:service_detail' service.pk %}">#</a>
                        </td>
                        <td>{{ service.title }}</td>
                        <td>{{ service.price|rus_money }}</td>
                        <td>{% firstof service.description|truncatechars:15|description_add '-пусто-'%}</td>
                    <tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <h3 class="lead">Услуг нет</h3>
    {% endif %}
{% endblock %}

ppnm1/templates/chess_spreadsheet/booking_detail.html
{% extends 'chess_base.html' %}
{% load user_filters %}

{% block title %}
    Бронь {{ booking.self }}
{% endblock %}

{% block header_brand %}
    Бронь
{% endblock %}

{% block content %}
    <div class="card mb-3">
        <div class="row g-0">
            <div class="card-body">
                <div class="col">
                    <div class="col-lg-6">
                        {% csrf_token %}
                        <table class="table table-borderless">
                            <tr>
                                <th>Клиент</th>
                                <td>
                                    <select class="form-control" id="client" onchange="set_booking()">
                                        {% for client in clients %}
                                            <option value="{{ client.pk }}" {% if client == booking.self.client %}selected{% endif %}>
                                                {{ client }}
                                            </option>
                                        {% endfor %}
                                    </select>
                                </td>
                            </tr>
                            <tr>
                                <th>Количество посетителей</th>
                                <td>
                                    <input class="form-control" type="number" id="customers_count" value="{{ booking.self.customers_count }}" onchange="set_booking()">
                                </td>
                            </tr>
                            <tr>
                                <th>Объект</th>
                                <td>
                                    <select class="form-control" id="object" onchange="set_booking()">
                                        {% for object in objects %}
                                            <option value="{{ object.pk }}" {% if object == booking.self.object %}selected{% endif %}>
                                                {{ object }}
                                            </option>
                                        {% endfor %}
                                    </select>
                                </td>
                            </tr>
                            <tr>
                                <th>Доп. услуги</th>
                                <td>
                                    <select class="form-control" id="services" onchange="set_booking()" multiple>
                                        {% for service in services %}
                                            <option value="{{ service.pk }}" {% if service in booking_services %}selected{% endif %}>
                                                {{ service }}
                                            </option>
                                        {% endfor %}
                                    </select>
                                </td>
                            </tr>
                            <tr>
                                <th>Дата брони</th>
                                <td>
                                    <input class="form-control" type="date" id="date" value="{{ booking_date }}" onchange="set_booking()">
                                </td>
                            </tr>
                            <tr>
                                <th>Время начала брони</th>
                                <td>
                                    <input class="form-control" type="time" id="time_from" value="{{ booking_time_from }}" onchange="set_booking()">
                                </td>
                            </tr>
                            <tr>
                                <th>Время конца брони</th>
                                <td>
                                    <input class="form-control" type="time" id="time_to" value="{{ booking_time_to }}" onchange="set_booking()">
                                </td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
        function set_booking() {
            $.ajax({
                url: '{% url 'chess:set_booking' %}',
                data: {
                    'client': $('#client').val(),
                    'customers_count': $('#customers_count').val(),
                    'object': $('#object').val(),
                    'services': $('#services').val(),
                    'date': $('#date').val(),
                    'time_from': $('#time_from').val(),
                    'time_to': $('#time_to').val(),
                    'booking_id': {{ booking.self.pk }}
                },
                dataType: 'json'
            });
            {% comment %} location.reload(); {% endcomment %}
        }
        $("input").focus(function(){
            if(this.value == this.defaultValue){
                this.select();
            }
        });
    </script>
{% endblock %}

ppnm1/templates/chess_spreadsheet/calc_game.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/calc_game.js' %}"></script>

    <title>Игра Калькулятор</title>
</head>
<body style="background-color: aqua;">
    <div class="p-5">
        <div class="card col-lg-3">
            <div class="card-header">
                <p>
                    Игра Калькулятор. Счёт <span style="color: green;" id="winCount">0</span>:<span style="color: red;" id="loseCount">0</span>
                </p>
                <p>
                    Прошло времени: <span id="timePassed">00:00</span>
                </p>
            </div>
            <div class="card-body">
                <h5 class="card-title">Сколько будет</h5>
                <p id='question' class="card-text">1 + 2 = <span id="result">?</span></p>
                <div class="row">
                    <button id="answer1">1</button>
                    <button id="answer2">2</button>
                    <button id="answer3">3</button>
                </div>
            </div>
            <div class="card-footer">
                <button id="correct" class="btn btn-success">Правильно</button>
                <button id="incorrect" class="btn btn-danger">Неверно</button>
            </div>
        </div>
    </div>
</body>
</html>

ppnm1/templates/chess_spreadsheet/chess.html
{% extends 'chess_base.html' %}
{% load user_filters %}

{% block title %}
    Шахматка
{% endblock %}

{% block head %}
    <style type="text/css">
        .table-responsive>.fixed-column {
            position: absolute;
            display: inline-block;
            width: auto;
            border-right: 1px solid #ddd;
            background-color: #fff;
        }
        td {
            max-width: 8rem;
        }
    </style>
{% endblock %}

{% block header_brand %}
    Почасовая шахматка
{% endblock %}

{% block content %}
    <div class="mb-3">
        <nav class="col-lg-3 offset-lg-9">
            <ul class="pagination justify-content-center">
                <li class="page-item">
                    <a class="page-link" href="{% url 'chess:chess' date|previous_day %}">&laquo;</a>
                </li>
                <li class="page-item">
                    <input class="page-link text-end" onkeydown="return false" type="date" value="{{ date|safe }}" onchange="dateRedirect(this);"/>
                </li>
                <li class="page-item">
                    <a class="page-link" href="{% url 'chess:chess' date|next_day %}">&raquo;</a>
                </li>
            </ul>
        </nav>
    </div>
    {% if objects %}
        <div class="table-responsive">
            <table class="table table-striped align-middle">
                <thead>
                    <tr class="text-left col-3">
                        <th scope="col">Объект</th>
                        {% for hour in time %}
                            <th>{{ hour|to_hour_format }}</th>
                        {% endfor %}
                    </tr>
                </thead>
                <tbody>
                    {% for object in objects %}
                        <tr>
                            <td scope="row">
                                <a class="nav-link" href="{% url 'chess:object_detail' object.pk %}">
                                    {{ object.title }}
                                </a>
                            </td>
                            {% for hour in time %}
                                <td id="{{ object.pk }}_{{ hour }}"></td>
                            {% endfor %}
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    {% else %}
        <h3 class="lead">На этот день броней нет</h3>
    {% endif %}
    <script>
        $(function() { // Функция постройки шахматки относительно б/д
            {% for booking in bookings %}
                cell = document.getElementById('{{ booking.booking.object.pk }}_{{ booking.time }}');
                cell.setAttribute('colspan', {{ booking.hours_count }});
                for (let i = 0; i < parseInt({{ booking.hours_count }}) - 1; i++) {
                    let id = parseInt({{ booking.time }}) + i + 1
                    document.getElementById('{{ booking.booking.object.pk }}_' + id).remove();
                }
                cell.innerHTML = '<a class="col-12 text-start btn ' +
                {% if booking.booking.status == '1' %} 'btn-info" title="Новая бронь"'
                {% elif booking.booking.status == '2' %} 'btn-primary" title="Ожидание клиент"'
                {% elif booking.booking.status == '3' %} 'btn-success" title="Клиент приехал"'
                {% elif booking.booking.status == '4' %} 'btn-secondary" title="Клиент уехал"'
                {% elif booking.booking.status == '5' %} 'btn-warning" title="Отмена"'
                {% endif %}
                + ' href="' + "{% url 'chess:booking_detail' booking.booking.pk %}" + '">{{ booking.booking|safe }}</a>';
            {% endfor %}
        });
        function dateRedirect(el) { // Переход на страницу даты
            window.location = '/chess/' + el.value;
        }
        $(function() { // Фиксированная левая колонка таблицы
            var $table = $('.table');
            //Make a clone of our table
            var $fixedColumn = $table.clone().insertBefore($table).addClass('fixed-column');
        
            //Remove everything except for first column
            $fixedColumn.find('th:not(:first-child),td:not(:first-child)').remove();
        
            //Match the height of the rows to that of the original table's
            $fixedColumn.find('tr').each(function (i, elem) {
                $(this).height($table.find('tr:eq(' + i + ')').height());
            });
        });
    </script>
{% endblock %}

ppnm1/templates/chess_spreadsheet/client_detail.html
{% extends 'chess_base.html' %}

{% block title %}
    Клиент {{ client.self }}
{% endblock %}

{% block header_brand %}
    Клиент
{% endblock %}

{% block content %}
    <div class="card mb-3">
        <div class="row g-0">
            <div class="card-body">
                <div class="col">
                    <div class="col-lg-6">
                        {% csrf_token %}
                        <table class="table table-borderless">
                            <tr>
                                <th>Имя</th>
                                <td>
                                    <input class="form-control" type="text" id="name" value="{{ client.self.name }}" onchange="set_client()">
                                </td>
                            </tr>
                            <tr>
                                <th>Телефон</th>
                                <td>
                                    <input class="form-control" type="tel" id="phone_number" value="{{ client.self.phone_number }}">
                                    <a style="text-decoration: none;" href="tel:{{ client.self.phone_number }}" onchange="set_client()">Позвонить</a>
                                </td>
                            </tr>
                            <tr>
                                <th>Email</th>
                                <td>
                                    <input class="form-control" type="email" id="email" value="{% firstof client.self.email '-пусто-' %}" onchange="set_client()">
                                </td>
                            </tr>
                        </table>
                    </div>
                </div>
                <div class="col">
                    <h3 class="lead">Все связанные брони</h3>
                    {% include 'includes/bookings_table_min.html' %}
                </div>
            </div>
        </div>
    </div>
    <script>
        function set_client() {
            $.ajax({
                url: '{% url 'chess:set_client' %}',
                data: {
                    'name': $('#name').val(),
                    'phone_number': $('#phone_number').val(),
                    'email': $('#email').val(),
                    'client_id': {{ client.self.pk }}
                },
                dataType: 'json'
            });
            location.reload();
        }
        $("input").focus(function(){
            if(this.value == this.defaultValue){
                this.select();
            }
        });
    </script>
{% endblock %}

ppnm1/templates/chess_spreadsheet/create_booking.html
{% extends 'chess_base.html' %}

{% block title %}
    Создание брони
{% endblock %}

{% block header_brand %}
    Создание брони
{% endblock %}

{% block content %}
    {% with 'chess:create_booking' as link and 'includes/form_body.html' as form_body %}
        {% include 'includes/create_card.html' %}
    {% endwith %}
{% endblock %}

ppnm1/templates/chess_spreadsheet/create_client.html
{% extends 'chess_base.html' %}

{% block title %}
    Создание клиента
{% endblock %}

{% block header_brand %}
    Создание клиента
{% endblock %}

{% block content %}
    {% with 'chess:create_client' as link and 'includes/form_body.html' as form_body %}
        {% include 'includes/create_card.html' %}
    {% endwith %}
{% endblock %}

ppnm1/templates/chess_spreadsheet/create_object.html
{% extends 'chess_base.html' %}

{% block title %}
    Создание объекта
{% endblock %}

{% block header_brand %}
    Создание объекта
{% endblock %}

{% block content %}
    {% with 'chess:create_object' as link and 'includes/form_body.html' as form_body %}
        {% include 'includes/create_card.html' %}
    {% endwith %}
{% endblock %}

ppnm1/templates/chess_spreadsheet/create_service.html
{% extends 'chess_base.html' %}

{% block title %}
    Создание услуги
{% endblock %}

{% block header_brand %}
    Создание услуги
{% endblock %}

{% block content %}
    {% with 'chess:create_service' as link and 'includes/form_body.html' as form_body %}
        {% include 'includes/create_card.html' %}
    {% endwith %}
{% endblock %}

ppnm1/templates/chess_spreadsheet/employee_window.html
{% extends 'chess_base.html' %}

{% block title %}
    Все брони
{% endblock %}

{% block header_brand %}
    Все брони
{% endblock %}

{% block content %}
    {% include 'includes/bookings_table.html' %}
{% endblock %}

ppnm1/templates/chess_spreadsheet/object_detail.html
{% extends 'chess_base.html' %}
{% load user_filters %}

{% block title %}
    Объект {{ object.self }}
{% endblock %}

{% block header_brand %}
    Объект
{% endblock %}

{% block content %}
    <div class="card mb-3">
        <div class="row g-0">
            <div class="card-body">
                <div class="col">
                    <div class="col-lg-6">
                        {% csrf_token %}
                        <table class="table table-borderless">
                            <tr>
                                <th>Название</th>
                                <td>
                                    <input class="form-control" type="text" id="title" value="{{ object.self.title }}" onchange="set_object()">
                                </td>
                            </tr>
                            <tr>
                                <th>Цена</th>
                                <td class="input-group">
                                    <input class="form-control" type="number" id="price" value="{{ object.self.price }}" onchange="set_object()">
                                    <div class="input-group-text">{{ ''|rus_money }}</div>
                                </td>
                            </tr>
                            <tr>
                                <th>Описание</th>
                                <td>
                                    <input class="form-control" type="text" id="description" value="{{ object.self.description }}" onchange="set_object()">
                                </td>
                            </tr>
                        </table>
                    </div>
                </div>
                <div class="col">
                    <h3 class="lead">Все связанные брони</h3>
                    {% include 'includes/bookings_table_min.html' %}
                </div>
            </div>
        </div>
    </div>
    <script>
        function set_object() {
            $.ajax({
                url: '{% url 'chess:set_object' %}',
                data: {
                    'title': $('#title').val(),
                    'price': $('#price').val(),
                    'description': $('#description').val(),
                    'object_id': {{ object.self.pk }}
                },
                dataType: 'json'
            });
            location.reload();
        }
        $("input").focus(function(){
            if(this.value == this.defaultValue){
                this.select();
            }
        });
    </script>
{% endblock %}