ppnm1/chess_spreadsheet/urls.py
from django.urls import path

from . import views, json_views, all_views, detail_views, create_views


app_name = 'chess'


urlpatterns = [
    path('set_booking_status/', json_views.set_booking_status, name='set_booking_status'),
    path('set_client/', json_views.set_client, name='set_client'),
    path('set_object/', json_views.set_object, name='set_object'),
    path('set_service/', json_views.set_service, name='set_service'),
    path('set_booking/', json_views.set_booking, name='set_booking'),
    
    path('objects/', all_views.objects, name='all_objects'),
    path('clients/', all_views.clients, name='all_clients'),
    path('bookings/', all_views.bookings, name='all_bookings'),
    path('services/', all_views.services, name='all_services'),

    path('objects/<int:pk>/', detail_views.object, name='object_detail'),
    path('clients/<int:pk>/', detail_views.client, name='client_detail'),
    path('bookings/<int:pk>/', detail_views.booking, name='booking_detail'),
    path('services/<int:pk>/', detail_views.service, name='service_detail'),

    path('objects/create/', create_views.object, name='create_object'),
    path('clients/create/', create_views.client, name='create_client'),
    path('bookings/create/', create_views.booking, name='create_booking'),
    path('services/create/', create_views.service, name='create_service'),

    path('calc_game/', views.calc_game, name='calc_game'),
    
	path('employee/', views.employee_window, name='employee'),
    path('<str:date>/', views.chess, name='chess'),


    path('', views.chess_today, name='chess_today')
]

ppnm1/main/urls.py
from django.conf import settings
from django.urls import path
from django.conf.urls.static import static

from . import views


app_name = 'main'


urlpatterns = [
    path('gallery/', views.gallery, name='gallery'),
    path('book/<int:pk>/', views.book, name='book'),
	path('', views.index, name='index'),
]


if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

ppnm1/ppnm1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404, handler500, handler403, handler400
from core.views import error_404, error_500


handler404 = error_404
handler500 = error_500


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('chess/', include('chess_spreadsheet.urls', namespace='chess')),
	path('', include('main.urls', namespace='main')),
]

ppnm1/templates/base.html
{% load static %}
{% with ver=113 %}
    <!DOCTYPE html>
    <!-- saved from url=(0014)about:internet -->
    <html lang="ru-RU">
        <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

            <link rel="icon" href="https://ppnm1.ru/favicon.ico?ver={{ ver }}" type="image/x-con">
            <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}?ver={{ ver }}">

            <meta name="description" content="Аренда мангальных полянок, аренда беседок, аренда домиков, рыбалка, бани, кемпинг, отдых на природе, рыбалка в Кашире"/>
            <meta name="robots" content="index"/>
            <meta name="apple-mobile-web-app-capable" content="yes"/>
            <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"/>
            <meta name="msapplication-TileColor" content="#990000"/>
            <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
            <meta name="theme-color" content="#013220">
            <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}?ver={{ ver }}">
            <link rel="stylesheet" href="{% static 'css/main.css' %}?ver={{ ver }}">
            
            {% block head %}{% endblock %}

            <title>
                {% block title %}{% endblock %}
            </title>
        </head>
        <body>
            {% block content %}{% endblock %}
        </body>
        {% include 'includes/footer.html' %}
    </html>
{% endwith %}

ppnm1/templates/chess_base.html
{% load static %}
{% with ver=108 %}
    <!DOCTYPE html>
    <html lang="ru-RU">
        <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

            <meta http-equiv="cleartype" content="on"/>
            <meta name="apple-mobile-web-app-capable" content="yes"/>
            <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"/>
            <meta name="msapplication-TileColor" content="#990000"/>
            <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
            <meta http-equiv="imagetoolbar" content="no"/>
            <meta http-equiv="msthemecompatible" content="no"/>
            <meta name="theme-color" content="#013220">
            <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}?ver={{ ver }}">
            <link rel="stylesheet" href="{% static 'css/bootstrap-reboot.min.css' %}?ver={{ ver }}">
            
            <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
            <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
            
            <style type="text/css">
                body {
                    -ms-user-select: none;
                    -moz-user-select: none;
                    -khtml-user-select: none;
                    -webkit-user-select: none;
                }
            </style>

            {% block head %}{% endblock %}

            <title>
                {% block title %}{% endblock %}
            </title>
        </head>
        <body>
            <div class="container">
                <header class="py-3 mx-3">
                    <nav class="navbar">
                        <div class="justify-content-start row mb-3">
                            <h3 class="navbar-brand col">
                                {% block header_brand %}{% endblock %}
                            </h3>
                            <div class="col">
                                {% block header_create %}{% endblock%}
                            </div>
                        </div>
                        {% with request.resolver_match.view_name as view_name %}
                            <ul class="nav nav-tabs">
                                <li class="nav-item"><a href="/chess/" aria-current="page" class="nav-link {% if view_name  == 'chess:chess' %}
                                    active {% endif %}">Шахматка</a></li>
                                <li class="nav-item dropdown">
                                    <a href="{% url 'chess:all_services' %}" class="nav-link dropdown-toggle
                                        {% if view_name in 'chess:all_services chess:all_objects chess:all_clients chess:all_bookings'  %}active{% endif %}"
                                        id="nav-all-dropdown" data-bs-toggle="dropdown" href="#" role="button" data-bs-auto-close="outside" aria-expanded="false">Все</a>
                                    <ul class="dropdown-menu" aria-labelledby="nav-all-dropdown">
                                        <li><a class="dropdown-item" href="{% url 'chess:all_services' %}">Услуги</a></li>
                                        <li><a class="dropdown-item" href="{% url 'chess:all_objects' %}">Объекты</a></li>
                                        <li><a class="dropdown-item" href="{% url 'chess:all_clients' %}">Клиенты</a></li>
                                        <li><a class="dropdown-item" href="{% url 'chess:all_bookings' %}">Брони</a></li>
                                    </ul>
                                </li>
                                <li class="nav-item"><a href="{% url 'chess:create_booking' %}" class="nav-link {% if view_name  == 'chess:create_booking' %}
                                    active {% endif %}">Новая бронь</a></li>
                            </ul>
                        {% endwith %}
                    </nav>
                </header>
                {% block content %}{% endblock %}
            </div>
        </body>
    </html>
{% endwith %}

ppnm1/templates/error_base.html
{% load static %}
<!DOCTYPE html>
{% with ver=104 %}
    <html lang="ru-RU">
        <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

            <link rel="icon" href="https://ppnm1.ru/favicon.ico?ver={{ ver }}" type="image/x-con">
            <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}?ver={{ ver }}">

            <meta http-equiv="cleartype" content="on"/>
            <meta name="apple-mobile-web-app-capable" content="yes"/>
            <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"/>
            <meta name="msapplication-TileColor" content="#990000"/>
            <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
            <meta http-equiv="imagetoolbar" content="no"/>
            <meta http-equiv="msthemecompatible" content="no"/>
            <meta name="theme-color" content="#013220">

            <style type="text/css">
                .center {
                    position: absolute;
                    top: 50%;
                    left: 50%;
                    -moz-transform: translateX(-50%) translateY(-50%);
                    -webkit-transform: translateX(-50%) translateY(-50%);
                    transform: translateX(-50%) translateY(-50%);
                    display: inline;
                }

                .lead{
                    font-size:1.25rem;
                    font-weight:300
                }

                .inline-block {
                    display: inline-block;
                    margin: 3rem 3rem;
                }
            </style>

            <title>
                {% block title %}{% endblock %}
            </title>
        </head>
        <body>
            <div class="center">
                <h1 class="inline-block">
                    {% block error_number %}{% endblock %}
                </h1>
                <div class="inline-block">
                    <h2 class="lead">
                        {% block error_text %}{% endblock %}
                    </h2>
                </div>
            </div>
        </body>
    </html>
{% endwith %}