ppnm1/chess_spreadsheet/urls.py
from django.urls import path

from . import views, json_views, all_views, detail_views, create_views


app_name = 'chess'


urlpatterns = [
    path('set_booking_status/', json_views.set_booking_status, name='set_booking_status'),
    path('set_client/', json_views.set_client, name='set_client'),
    path('set_object/', json_views.set_object, name='set_object'),
    path('set_service/', json_views.set_service, name='set_service'),
    path('set_booking/', json_views.set_booking, name='set_booking'),
    
    path('objects/', all_views.objects, name='all_objects'),
    path('clients/', all_views.clients, name='all_clients'),
    path('bookings/', all_views.bookings, name='all_bookings'),
    path('services/', all_views.services, name='all_services'),

    path('objects/<int:pk>/', detail_views.object, name='object_detail'),
    path('clients/<int:pk>/', detail_views.client, name='client_detail'),
    path('bookings/<int:pk>/', detail_views.booking, name='booking_detail'),
    path('services/<int:pk>/', detail_views.service, name='service_detail'),

    path('objects/create/', create_views.object, name='create_object'),
    path('clients/create/', create_views.client, name='create_client'),
    path('bookings/create/', create_views.booking, name='create_booking'),
    path('services/create/', create_views.service, name='create_service'),

    path('calc_game/', views.calc_game, name='calc_game'),
    
	path('employee/', views.employee_window, name='employee'),
    path('<str:date>/', views.chess, name='chess'),


    path('', views.chess_today, name='chess_today')
]

ppnm1/main/urls.py
from django.conf import settings
from django.urls import path
from django.conf.urls.static import static

from . import views


app_name = 'main'


urlpatterns = [
    path('gallery/', views.gallery, name='gallery'),
    path('book/<int:pk>/', views.book, name='book'),
	path('', views.index, name='index'),
]


if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

ppnm1/ppnm1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404, handler500, handler403, handler400
from core.views import error_404, error_500


handler404 = error_404
handler500 = error_500


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('chess/', include('chess_spreadsheet.urls', namespace='chess')),
	path('', include('main.urls', namespace='main')),
]

ppnm1/templates/includes/bookings_table.html
<style type="text/css">
    td {
        
    }
</style>
{% if bookings %}
    <div class="table-responsive">
        <table class="table table-striped">
            <thead class="text-center">
                <tr>
                    <th></th>
                    <th scope="col">Состояние</th>
                    <th scope="col">Клиент</th>
                    <th scope="col">Посетителей</th>
                    <th scope="col">Объект</th>
                    <th scope="col">Услуги</th>
                    <th scope="col">Дата</th>
                    <th scope="col">Время начала</th>
                    <th scope="col">Время конца</th>
                </tr>
            </thead>
            <tbody class="align-middle text-center">
                {% for booking in bookings %}
                    <tr>
                        <td>
                            <a style="text-decoration:none;" href="{% url 'chess:booking_detail' booking.pk %}">#</a>
                        </td>
                        <td>
                            <select onchange="set_booking_status(this, {{ booking.pk }});">
                                {% for option in booking.STATUS_CHOICES %}
                                    <option value="{{ option.0 }}" {% if booking.status == option.0 %} selected {% endif %}> 
                                        {{ option.1 }}
                                    </option>
                                {% endfor %}
                            </select>
                        </td>
                        <td>
                            <a style="text-decoration:none;" href="{% url 'chess:client_detail' booking.client.pk %}"> {{ booking.client }} </a>
                        </td>
                        <td> {{ booking.customers_count }} </td>
                        <td>
                            <a style="text-decoration:none;" href="{% url 'chess:object_detail' booking.object.pk %}"> {{ booking.object.title }} </a>
                        </td>
                        {% with services=booking.services.all id=booking.pk %}
                            <td><a style="text-decoration:none;" href="#" data-bs-toggle="modal" data-bs-target="#servicesModal{{ id }}">
                                {{ services.count }}
                            </a></td>
                            {% include 'includes/services_modal.html' %}
                        {% endwith %}
                        <td>{{ booking.date }}</td>
                        <td>{{ booking.time_from }}</td>
                        <td>{{ booking.time_to }}</td>
                    <tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% else %}
    <h3 class="lead">Броней нет</h3>
{% endif %}
<script>
    function set_bkg(el) {
        const bkg = {
            '1': 'bg-info',
            '2': 'bg-primary',
            '3': 'bg-success',
            '4': 'bg-secondary',
            '5': 'bg-warning'
        };
        el.className = 'from-control no-border text-white badge border-0 ' + bkg[el.value];
    }
    function set_booking_status(el, booking_id) {
        set_bkg(el);
        $.ajax({
            url: '{% url 'chess:set_booking_status' %}',
            data: {
                'value': el.value,
                'booking_id': booking_id
            },
            dataType: 'json'
        });
    }
    window.onload = $('select').each(function(){set_bkg($(this).get(0))});
</script>

ppnm1/templates/includes/bookings_table_min.html
{% load user_filters %}
<div class="table-responsive">
    <table class="table table-striped">
        <thead class="text-center">
            <tr>
                <th></th>
                {% if not client %}
                    <th scope="col">Клиент</th>
                {% endif %}
                {% if not object %}
                    <th scope="col">Объкет</th>
                {% endif %}
                <th scope="col">Стоимость</th>
            </tr>
        </thead>
        <tbody class="align-middle text-center">
            {% for booking in bookings %}
                <tr>
                    <td><a class="nav-link" href="{% url 'chess:booking_detail' booking.pk %}">
                        #
                    </a></td>
                    {% if not client %}
                        <td><a class="nav-link" href="{% url 'chess:client_detail' booking.client.pk %}">
                            {{ booking.client }}
                        </a></td>
                    {% endif %}
                    {% if not object %}
                        <td><a class="nav-link" href="{% url 'chess:object_detail' booking.object.pk %}">
                            {{ booking.object.title }}
                        </a></td>
                    {% endif %}
                    <td>{{ booking.get_sum|rus_money }}</td>
                <tr>
            {% endfor %}
        </tbody>
    </table>
</div>

ppnm1/templates/includes/create_card.html
<div class="card">
    <div class="card-body">
        {% include 'includes/form_errors.html' %}
        <form method="post" action="{% url link %}">
            {% include form_body %}
            <button type="submit" class="btn btn-primary">Сохранить</button>
        </form>
    </div>
</div>

ppnm1/templates/includes/footer.html
{% load static %}
<footer class="background-tile-1 text-white">
    <div>
        <div class="row mb-3">
            <div class="mb-4">
                <h2 class="mb-3">Уточнить детали и договориться о посещении Пикник-парка «Наше место»<br>Вы можете по этим контактам:</h2>
                <h2 class="mb-1"><a href="tel:+79295550066">+79295550066</a></h2>
                <h2 class="mb-1"><a href="mailto:picnik-park@yandex.ru">picnik-park@yandex.ru</a></h2>
                <h2><a href="https://vk.com/ppnm1" id="vk_groups_mobile">Группа VK</a></h2>
            </div>
            <div class="col">
                <div class="row-3 mb-3"><a class="btn main-button" href="{% static 'files/rules.pdf' %}">
                    <h3 class="gold">Правила парка и прайс-лист</h3>
                </a></div>
                <div class="row-3 mb-3">
                    <a class="btn main-button" href="{% static 'files/camping_rules.pdf' %}">
                        <h3 class="gold">Правила кемпинга</h3>
                    </a>
                </div>
                <div class="row-3">
                    <a class="btn main-button" href="{% static 'files/fishing_rules.pdf' %}">
                        <h3 class="gold">Правила суточной рыбалки</h3>
                    </a>
                </div>
            </div>
        </div>
        <p>© 2022 ИП Шишкин П. А.</p>
    </div>
</footer>

ppnm1/templates/includes/form_body.html
{% load user_filters %}
{% csrf_token %}
{% for field in form %}
  <div class="form-group row my-3"
        {% if field.field.required %} 
            aria-required="true"
        {% else %}
            aria-required="false"
        {% endif %}
        >
        <label for="{{ field.id_for_label }}">
            {{ field.label }}
            {% if field.field.required %}
                <span class="required text-danger">*</span>
            {% endif %}
        </label>
        <div>
            {{ field|addclass:'form-control' }}
            {% if field.help_text %}
            <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                {{ field.help_text|safe }}
            </small>
            {% endif %}
        </div>
    </div>
{% endfor %}

ppnm1/templates/includes/form_body_booking.html
{% load user_filters %}
{% csrf_token %}
{% with form.client as field %}
    <div class="form-group row my-3"
    {% if field.field.required %} 
        aria-required="true"
    {% else %}
        aria-required="false"
    {% endif %}
    >
    <label for="{{ field.id_for_label }}">
        {{ field.label }}
        {% if field.field.required %}
            <span class="required text-danger">*</span>
        {% endif %}
    </label>
    <div>
        {{ field|addclass:'form-control' }}
        {% if field.help_text %}
        <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
            {{ field.help_text|safe }}
        </small>
        {% endif %}
    </div>
    </div>
{% endwith %}
{% with form.customers_count as field %}
    <div class="form-group row my-3"
    {% if field.field.required %} 
        aria-required="true"
    {% else %}
        aria-required="false"
    {% endif %}
    >
    <label for="{{ field.id_for_label }}">
        {{ field.label }}
        {% if field.field.required %}
            <span class="required text-danger">*</span>
        {% endif %}
    </label>
    <div>
        {{ field|addclass:'form-control' }}
        {% if field.help_text %}
        <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
            {{ field.help_text|safe }}
        </small>
        {% endif %}
    </div>
    </div>
{% endwith %}
{% with form.object as field %}
    <div class="form-group row my-3"
    {% if field.field.required %} 
        aria-required="true"
    {% else %}
        aria-required="false"
    {% endif %}
    >
    <label for="{{ field.id_for_label }}">
        {{ field.label }}
        {% if field.field.required %}
            <span class="required text-danger">*</span>
        {% endif %}
    </label>
    <div>
        {{ field|addclass:'form-control' }}
        {% if field.help_text %}
        <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
            {{ field.help_text|safe }}
        </small>
        {% endif %}
    </div>
    </div>
{% endwith %}
{% with form.services as field %}
    <div class="form-group row my-3"
    {% if field.field.required %} 
        aria-required="true"
    {% else %}
        aria-required="false"
    {% endif %}
    >
    <label for="{{ field.id_for_label }}">
        {{ field.label }}
        {% if field.field.required %}
            <span class="required text-danger">*</span>
        {% endif %}
    </label>
    <div>
        {{ field|addclass:'form-control' }}
        {% if field.help_text %}
        <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
            {{ field.help_text|safe }}
        </small>
        {% endif %}
    </div>
    </div>
{% endwith %}
{% with form.date as field %}
    <div class="form-group row my-3"
    {% if field.field.required %} 
        aria-required="true"
    {% else %}
        aria-required="false"
    {% endif %}
    >
    <label for="{{ field.id_for_label }}">
        {{ field.label }}
        {% if field.field.required %}
            <span class="required text-danger">*</span>
        {% endif %}
    </label>
    <div>
        {{ field|addclass:'form-control' }}
        {% if field.help_text %}
        <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
            {{ field.help_text|safe }}
        </small>
        {% endif %}
    </div>
    </div>
{% endwith %}
{% with form.time_from as field %}
    <div class="form-group row my-3"
    {% if field.field.required %} 
        aria-required="true"
    {% else %}
        aria-required="false"
    {% endif %}
    >
    <label for="{{ field.id_for_label }}">
        {{ field.label }}
        {% if field.field.required %}
            <span class="required text-danger">*</span>
        {% endif %}
    </label>
    <div>
        {{ field|addclass:'form-control' }}
        {% if field.help_text %}
        <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
            {{ field.help_text|safe }}
        </small>
        {% endif %}
    </div>
    </div>
{% endwith %}
{% with form.time_to as field %}
    <div class="form-group row my-3"
    {% if field.field.required %} 
        aria-required="true"
    {% else %}
        aria-required="false"
    {% endif %}
    >
    <label for="{{ field.id_for_label }}">
        {{ field.label }}
        {% if field.field.required %}
            <span class="required text-danger">*</span>
        {% endif %}
    </label>
    <div>
        {{ field|addclass:'form-control' }}
        {% if field.help_text %}
        <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
            {{ field.help_text|safe }}
        </small>
        {% endif %}
    </div>
    </div>
{% endwith %}

ppnm1/templates/includes/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}            
            <div class="alert alert-danger">
                {{ error|escape }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            {{ error|escape }}
        </div>
    {% endfor %}
{% endif %}

ppnm1/templates/includes/offcanvas_card_create.html
<div class="offcanvas offcanvas-end" tabindex="-1" id="{{ offcanvas_name }}" aria-labelledby="{{ offcanvas_name }}Label">
    <div class="offcanvas-header">
        <h5 id="{{ offcanvas_name }}Label">{{ link }}</h5>
        <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body">
        {% include 'includes/create_card.html' %}
    </div>
</div>

ppnm1/templates/includes/services_modal.html
<div class="modal fade" id="servicesModal{{ id }}" tabindex="-1" aria-labelledby="servicesModal{{ id }}Label" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="servicesModal{{ id }}Label">Услуги</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <ul class="nav flex-column">
                    {% for service in services %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'chess:service_detail' service.pk %}">{{ service.title }}</a></li>
                    {% empty %}
                        Услуг нет
                    {% endfor %}
                </ul>
            </div>
            <div class="modal-footer">
            </div>
        </div>
    </div>
</div>

ppnm1/templates/includes/yandex_metrika.html
<!-- Yandex.Metrika counter -->
<script>
    (function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};
    m[i].l=1*new Date();k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)})
    (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");
 
    ym(88406001, "init", {
         clickmap:true,
         trackLinks:true,
         accurateTrackBounce:true,
         webvisor:true
    });
 </script>
 <noscript><div><img src="https://mc.yandex.ru/watch/88406001" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
 <!-- /Yandex.Metrika counter -->